CREATE DATABASE catalog;
USE catalog;

CREATE TABLE book(id INT GENERATED BY DEFAULT AS IDENTITY, 
publisher VARCHAR, cover_state VARCHAR, archived BOOLEAN,FOREIGN KEY(label_id) REFERENCES label(id)
);

CREATE TABLE label(id INT GENERATED BY DEFAULT AS IDENTITY, title VARCHAR, color VARCHAR, PRIMARY KEY (id))

CREATE TABLE music_albums (
  id INT GENERATED ALWAYS AS IDENTITY,
  FOREIGN KEY(genre_id) REFERENCES genre(id) 
  FOREIGN KEY(author_id) REFERENCES author(id) 
  FOREIGN KEY(source_id) REFERENCES source(id) 
  publish_date DATE,
  archived BOOLEAN,
  on_spotify BOOLEAN,
);

CREATE TABLE genres (
  id INT GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(100)
);